//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model.Template
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CashDepositMgtSys : DbContext
    {
        public CashDepositMgtSys()
            : base("name=CashDepositMgtSys")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agency> agency { get; set; }
        public virtual DbSet<deducted> deducted { get; set; }
        public virtual DbSet<generation_buckle> generation_buckle { get; set; }
        public virtual DbSet<generation_gives> generation_gives { get; set; }
        public virtual DbSet<staff> staff { get; set; }
    }
}
