//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model.Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class deducted
    {
        public int id { get; set; }
        public Nullable<int> generation_gives_id { get; set; }
        public string item { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string remark { get; set; }
    }
}
