//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Model.Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class generation_gives
    {
        public int id { get; set; }
        public Nullable<System.DateTime> record_date { get; set; }
        public string recorder_code { get; set; }
        public string reviewer_code { get; set; }
        public Nullable<int> review_state { get; set; }
        public Nullable<System.DateTime> review_date { get; set; }
        public string agency_code { get; set; }
        public string salesman_name { get; set; }
        public string salesman_sex { get; set; }
        public string salesman_card_type { get; set; }
        public string salesman_card_id { get; set; }
        public string salesman_phone { get; set; }
        public string salesman_bank_account_name { get; set; }
        public string salesman_bank_account_number { get; set; }
        public string salesman_bank_name { get; set; }
        public string salesman_bank_province { get; set; }
        public string salesman_bank_city { get; set; }
        public string salesman_subbank_name { get; set; }
        public Nullable<decimal> salesman_cash_deposit { get; set; }
        public Nullable<decimal> salesman_refunds { get; set; }
        public Nullable<int> salesman_refunds_state { get; set; }
        public string remark { get; set; }
    }
}
