// <auto-generated />
namespace Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mio_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mio_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201702281001175_mio_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
